module.exports = {
    models : [
        {name: 'tvData', directory: '/assets/models/tv-model.json'},
        {name: 'tvController', directory: '/assets/models/tv-controller4.json'}
    ],
    images : [
        {name: 'portrait',                  directory: '/assets/about/kenji.jpg'},
        {name: 'name',                      directory: '/assets/about/name.jpg'},
        {name: 'job',                       directory: '/assets/about/job.jpg'},
        {name: 'company',                   directory: '/assets/about/company.jpg'},
        {name: 'age',                       directory: '/assets/about/age.jpg'},
        {name: 'linkedin',                  directory: '/assets/about/linkedin.jpg'},
        {name: 'live',                      directory: '/assets/about/live.jpg'},
        {name: 'japan',                     directory: '/assets/about/japan.jpg'},
        {name: 'skills',                    directory: '/assets/about/skills.jpg'},
        {name: 'leftArrow',                 directory: '/assets/indicator/left-arrow.jpg'},
        {name: 'thumbnailXFile',            directory: '/assets/works/thumbnail/x-file.jpg'},
        {name: 'mainXFile',                 directory: '/assets/works/main/x-file.jpg'},
        {name: 'thumbnailCapitolCouture',   directory: '/assets/works/thumbnail/capitol-couture.jpg'},
        {name: 'mainCapitolCouture',        directory: '/assets/works/main/capitol-couture.jpg'},
        {name: 'thumbnailStrokeForLove',    directory: '/assets/works/thumbnail/stroke-for-love.jpg'},
        {name: 'mainStrokeForLove',         directory: '/assets/works/main/stroke-for-love.jpg'},
        {name: 'thumbnailMinorityReport',   directory: '/assets/works/thumbnail/minority-report.jpg'},
        {name: 'mainMinorityReport',        directory: '/assets/works/main/minority-report.jpg'},
        {name: 'thumbnailKoheiNawa',        directory: '/assets/works/thumbnail/kohei-nawa.jpg'},
        {name: 'mainKoheiNawa',             directory: '/assets/works/main/kohei-nawa.jpg'},
        {name: 'thumbnailHug',              directory: '/assets/works/thumbnail/hug.jpg'},
        {name: 'mainHug',                   directory: '/assets/works/main/hug.jpg'},
        {name: 'thumbnailMucca',            directory: '/assets/works/thumbnail/mucca.jpg'},
        {name: 'mainMucca',                 directory: '/assets/works/main/mucca.jpg'},
        {name: 'thumbnailMlp',              directory: '/assets/works/thumbnail/mlp.jpg'},
        {name: 'mainMlp',                   directory: '/assets/works/main/mlp.jpg'},
        {name: 'thumbnailMore',             directory: '/assets/works/thumbnail/more.jpg'},
        {name: 'contactMail',               directory: '/assets/contact/mail.jpg'},
        {name: 'contactCodepen',            directory: '/assets/contact/codepen.jpg'},
        {name: 'contactFacebook',           directory: '/assets/contact/facebook.jpg'},
        {name: 'contactGithub',             directory: '/assets/contact/github.jpg'},
        {name: 'contactLinkedin',           directory: '/assets/contact/linkedin.jpg'},
        {name: 'contactPinterest',          directory: '/assets/contact/pinterest.jpg'},
        {name: 'contactTumblr',             directory: '/assets/contact/tumblr.jpg'},
        {name: 'contactTwitter',            directory: '/assets/contact/twitter.jpg'},
        {name: 'contactInstgram',           directory: '/assets/contact/instgram.jpg'},
        {name: 'sketchCS',                  directory: '/assets/sketch/cs.jpg'},
        {name: 'sketch2DPhy',               directory: '/assets/sketch/2d-phy.jpg'},
        {name: 'sketchCanvasTest',          directory: '/assets/sketch/canvas-test.jpg'},
        {name: 'sketchGreeting',            directory: '/assets/sketch/greeting.jpg'},
        {name: 'sketchVoronoiBody',         directory: '/assets/sketch/voronoi-body.jpg'},
        {name: 'sketchWaterPaint',          directory: '/assets/sketch/water-paint.jpg'},
        {name: 'sketchWebGlDojo',           directory: '/assets/sketch/webgl-dojo.jpg'},
        {name: 'audioOn',                   directory : '/assets/sounds/audio-on.jpg'},

        {name: 'spParticle',                directory : '/assets/special/particle2.png'},
        {name: 'spPerlin',                directory : '/assets/special/perlin-512.png'},
        {name: 'spBg',                directory : '/assets/special/bg.png'},
    ],
    json : [
        {name : "workData",    directory : '/assets/json/works.json'},
        {name : "contactData", directory : '/assets/json/contact.json'},
        {name : "sketchData", directory : '/assets/json/sketch.json'},
    ]


};